#!/bin/bash
# init.sh — Development environment setup
# Generated by quest init

set -e

echo "==> Installing dependencies..."

# Install Node.js dependencies if package.json exists
if [ -f package.json ]; then
  npm install 2>&1
fi

echo "Quest harness is ready."
echo "Usage:"
echo "  quest run [dir]    # Run the full orchestration loop"
echo "  quest status [dir] # Show feature progress"
