/**
 * Direct scaffold file creation for `quest init`.
 *
 * Creates the three required files (init.sh, features.json, claude-progress.txt)
 * without requiring an AI agent. This is the "basic" initialization path.
 */

import { writeFile, chmod } from 'node:fs/promises'
import { join } from 'node:path'
import type { FeaturesFile, Feature } from './agents/types.js'
import { createInitialProgress, writeProgress } from './state/progress.js'
import { writeFeaturesFile } from './state/features.js'

const BASIC_INIT_SH = `#!/bin/bash
# init.sh — Development environment setup
# Generated by quest init

set -e

echo "==> Installing dependencies..."

# Install Node.js dependencies if package.json exists
if [ -f package.json ]; then
  npm install 2>&1
fi

echo "Quest harness is ready."
echo "Usage:"
echo "  quest run [dir]    # Run the full orchestration loop"
echo "  quest status [dir] # Show feature progress"
`

/**
 * Generate a set of placeholder features for the scaffold.
 * The evaluator requires at least 10.
 */
function buildPlaceholderFeatures(projectName: string): Feature[] {
  const categories: Array<Feature['category']> = ['api', 'ui', 'auth', 'data', 'ux']
  const priorities: Array<Feature['priority']> = ['high', 'high', 'medium', 'medium', 'low']

  const templates: Array<Omit<Feature, 'id' | 'category' | 'priority'>> = [
    {
      name: 'Project Setup',
      description: 'Initialize the project structure and development environment',
      acceptanceCriteria: [
        'Project directory structure is created',
        'Dependencies are installed',
        'Development server starts without errors',
      ],
      passes: false,
    },
    {
      name: 'Hello World Endpoint',
      description: 'Create a basic health-check or hello-world API endpoint',
      acceptanceCriteria: [
        'Endpoint responds with HTTP 200',
        'Response body contains expected message',
      ],
      passes: false,
    },
    {
      name: 'Basic Authentication',
      description: 'Implement user login and logout functionality',
      acceptanceCriteria: [
        'User can log in with valid credentials',
        'Invalid credentials return an error',
        'Authenticated session is maintained',
      ],
      passes: false,
    },
    {
      name: 'User Registration',
      description: 'Allow new users to create accounts',
      acceptanceCriteria: [
        'Registration form validates required fields',
        'Duplicate emails are rejected',
        'New user is persisted to the database',
      ],
      passes: false,
    },
    {
      name: 'Data Persistence',
      description: 'Connect the application to a persistent data store',
      acceptanceCriteria: [
        'Application connects to the database on startup',
        'Data survives a server restart',
      ],
      passes: false,
    },
    {
      name: 'Input Validation',
      description: 'Validate and sanitize all user-supplied inputs',
      acceptanceCriteria: [
        'Invalid input returns a descriptive error message',
        'SQL injection and XSS inputs are rejected or escaped',
      ],
      passes: false,
    },
    {
      name: 'Error Handling',
      description: 'Return structured error responses for all failure cases',
      acceptanceCriteria: [
        'Errors include a human-readable message',
        'HTTP status codes are appropriate (4xx for client, 5xx for server)',
      ],
      passes: false,
    },
    {
      name: 'Logging',
      description: 'Log application events and errors',
      acceptanceCriteria: [
        'Errors are logged with stack traces',
        'Request/response cycles are logged at info level',
      ],
      passes: false,
    },
    {
      name: 'Configuration Management',
      description: 'Support environment-specific configuration via environment variables',
      acceptanceCriteria: [
        'Application reads config from environment variables',
        'Missing required config fails fast with a clear message',
      ],
      passes: false,
    },
    {
      name: 'Basic UI Layout',
      description: 'Create the main application layout with navigation',
      acceptanceCriteria: [
        'Layout renders without errors',
        'Navigation links are visible and functional',
        'Layout is responsive on mobile and desktop',
      ],
      passes: false,
    },
    {
      name: 'List View',
      description: 'Display a paginated list of main resource items',
      acceptanceCriteria: [
        'List renders items from the data source',
        'Empty state is shown when no items exist',
        'Pagination controls appear when items exceed page size',
      ],
      passes: false,
    },
    {
      name: 'Detail View',
      description: 'Show full details for a single resource item',
      acceptanceCriteria: [
        'Detail page loads from item ID in URL',
        '404 page shown for unknown IDs',
      ],
      passes: false,
    },
    {
      name: 'Create Form',
      description: 'Form to create a new resource item',
      acceptanceCriteria: [
        'Form validates required fields before submit',
        'Successful submission redirects to the new item',
        'Server-side errors are displayed inline',
      ],
      passes: false,
    },
    {
      name: 'Edit Form',
      description: 'Form to update an existing resource item',
      acceptanceCriteria: [
        'Form pre-fills current values',
        'Changes are persisted on submit',
      ],
      passes: false,
    },
    {
      name: 'Delete Action',
      description: 'Allow users to delete a resource item',
      acceptanceCriteria: [
        'User is prompted to confirm before deletion',
        'Item is removed from the data store after confirmation',
      ],
      passes: false,
    },
  ]

  return templates.map((t, i) => ({
    id: `${t.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}-${i + 1}`,
    category: categories[i % categories.length]!,
    priority: priorities[i % priorities.length]!,
    ...t,
  }))
}

/**
 * Create the three scaffold files in the target directory.
 *
 * @param projectDir  Absolute path to the project directory (must exist)
 * @param projectName Human-readable project name
 */
export async function createBasicScaffold(
  projectDir: string,
  projectName: string,
): Promise<void> {
  const features = buildPlaceholderFeatures(projectName)

  const featuresFile: FeaturesFile = {
    version: '1.0',
    projectName,
    generatedAt: new Date().toISOString(),
    features,
  }

  const initShPath = join(projectDir, 'init.sh')

  await Promise.all([
    // 1. init.sh
    writeFile(initShPath, BASIC_INIT_SH, 'utf-8').then(() => chmod(initShPath, 0o755)),
    // 2. features.json
    writeFeaturesFile(projectDir, featuresFile),
    // 3. claude-progress.txt
    writeProgress(projectDir, createInitialProgress(projectName, features.length)),
  ])
}
